export const ARTPLAYER_I18N = {
	vi: {
		Play: "Phát",
		Screenshot: "Chụp ảnh",
		"Show Setting": "Hiện lựa chọn",
		"PIP Mode": "Chế độ PiP",
		"Web Fullscreen": "Tràn viền",
		Fullscreen: "Toàn màn",
		"Play Speed": "Tốc độ phát",
		"Aspect Ratio": "Tỉ lệ",
		"Video Flip": "Lật",
		Horizontal: "Chiều ngang",
		Vertical: "Chiều dọc",
		Normal: "Bình thường",
		Pause: "Tạm dừng",
		"Exit Fullscreen": "Thoát",
		"Exit PIP Mode": "Thoát PiP",
		"Exit Web Fullscreen": "Thoát",
		Default: "Mặc định",
		Volume: "Âm lượng",
	},
}

export const ARTPLAYER_BASIC_SETTINGS = {
	theme: "#a855f7",
	isLive: false,
	muted: false,
	autoplay: true,
	pip: true,
	autoSize: false,
	autoMini: true,
	screenshot: true,
	setting: true,
	loop: false,
	flip: true,
	playbackRate: true,
	aspectRatio: true,
	fullscreen: true,
	fullscreenWeb: true,
	subtitleOffset: false,
	miniProgressBar: true,
	mutex: true,
	backdrop: true,
	playsInline: true,
	autoPlayback: false,
	airplay: true,
	lock: true,
	gesture: true,
	fastForward: true,
	autoOrientation: true,
	lang: "vi",
}
